### ISSUE TITLE
Does this support Bokeh widgets?

### ISSUE THREAD

**Issue by chetanambi** [NuCOS/angular-bokeh#3]
Hi - Is it possible to display bokeh [widgets ](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#adding-widgets) (button, daterange etc.) along with the plot? I tried to simple button but it's not showing the graph. And there are no errors also in the command line. Do you have any suggestions?

from bokeh.models import Button

```
class ChartProvider():
    def __init__(self):
        self.phi = 0

    def chartExample(self):
        t0 = time.time()

        # prepare some data
        self.phi += 0.02
        x = np.arange(0., 10., 0.1)
        y = np.sin(x + self.phi)

        # create a new plot
        p = figure()
        p.line(x, y, legend="SIN")
        button = Button(label="Foo", button_type="success")
        layout = column(row(button), row(p))
        chart_item = json_item(layout)
        print(time.time()-t0)
        return chart_item
```

**Comment by DocBO** [comment]
Hi, the magic happens in the bokeh api on js side here: embed_item. Alongside with the buttons comes JS code and I guess this is not working since the JS libs are missing. See: https://docs.bokeh.org/en/latest/docs/first_steps/installation.html#install-bokehjs for more details how to import this in the html.
We put this import in the index.html as usual. We skipped e.g. widgets but you can include if you need this.

**Comment by chetanambi** [comment]
Thanks again! After including BokehJS for widgets, it's working. 

![image](https://user-images.githubusercontent.com/37707687/119809749-0f740180-bf03-11eb-991a-61a72519b46b.png)
