### ISSUE TITLE
Require() doesn't work with CustomJS

### ISSUE THREAD

**Issue by chetanambi** [NuCOS/angular-bokeh#4]
Hi - I am trying to use **danfojs-node** within CustomJS using require as shown below but running into an error. Do you have any suggestions on how to get this working?

```
callback = CustomJS(args=dict(source=source), code="""
                    const dfd = require("danfojs-node")
                    ... some other code..
                    """)
```

Error from Chrome Developer tools for require() function

![image](https://user-images.githubusercontent.com/37707687/120490346-f624f680-c3d5-11eb-9237-6abedead9b26.png)

**Comment by DocBO** [comment]
Hello - I have not tried to mix these things up. You have also not tried to stretch the bokeh CustomJS since it may or may not interfere with Angular or/and is even not compatible with require.
require is here the problem: see e.g. https://stackoverflow.com/questions/23603514/javascript-require-function-giving-referenceerror-require-is-not-defined

**Comment by chetanambi** [comment]
Yes, require() is a server-side method and won't work on client-side such as browsers. Though it we try browserify, I will look for other alternatives on how to create dynamic charts. Thanks again!
